{ config, lib, pkgs, ... }:

let
  cfg    = config.ft.desktop.river;
  term   = config.ft.desktop.terminal;
  mod    = "Super";

  # River uses bitmask tags instead of numbered workspaces.
  # tag N = (1 << (N-1)):  1 2 4 8 16 32 64 128 256
  # We generate the riverctl calls in a shell loop inside the init script.

  layoutCmd =
    if cfg.layout == "rivertile"
    then "rivertile -view-padding 5 -outer-padding 10 -main-ratio ${toString cfg.mainRatio} -main-count ${toString cfg.mainCount} &"
    else "stacktile &";

  initScript = ''
    #!/usr/bin/env bash
    # ── River init — generated by ft-nixlaunch home module ──────────────────

    mod="${mod}"

    # ── Input ────────────────────────────────────────────────────────────────
    riverctl keyboard-layout de

    riverctl input "type:touchpad" natural-scroll    enabled
    riverctl input "type:touchpad" tap               enabled
    riverctl input "type:touchpad" disable-while-typing enabled

    # ── Appearance ───────────────────────────────────────────────────────────
    riverctl border-width 2

    # ── Apps ─────────────────────────────────────────────────────────────────
    riverctl map normal $mod Return  spawn '${term}'
    riverctl map normal $mod Space   spawn 'ft-nixlaunch'
    riverctl map normal $mod B       spawn 'firefox'
    riverctl map normal $mod E       spawn '${term} -e yazi'

    # ── Window management ────────────────────────────────────────────────────
    riverctl map normal $mod       Q close
    riverctl map normal $mod+Shift Q exit
    riverctl map normal $mod       F toggle-fullscreen
    riverctl map normal $mod       V toggle-float

    # ── Focus (vim-style) ────────────────────────────────────────────────────
    riverctl map normal $mod H focus-view left
    riverctl map normal $mod L focus-view right
    riverctl map normal $mod K focus-view up
    riverctl map normal $mod J focus-view down

    # ── Move windows ─────────────────────────────────────────────────────────
    riverctl map normal $mod+Shift H swap left
    riverctl map normal $mod+Shift L swap right
    riverctl map normal $mod+Shift K swap up
    riverctl map normal $mod+Shift J swap down

    # ── Layout ───────────────────────────────────────────────────────────────
    riverctl map normal $mod Period  send-layout-cmd rivertile "main-ratio +0.05"
    riverctl map normal $mod Comma   send-layout-cmd rivertile "main-ratio -0.05"
    riverctl map normal $mod+Shift I send-layout-cmd rivertile "main-count +1"
    riverctl map normal $mod+Shift D send-layout-cmd rivertile "main-count -1"

    # Cycle layout orientation
    riverctl map normal $mod Up    send-layout-cmd rivertile "main-location top"
    riverctl map normal $mod Right send-layout-cmd rivertile "main-location right"
    riverctl map normal $mod Down  send-layout-cmd rivertile "main-location bottom"
    riverctl map normal $mod Left  send-layout-cmd rivertile "main-location left"

    # ── Tags (workspaces) ────────────────────────────────────────────────────
    # River uses bitmask tags:  tag N = 1 << (N-1)
    for i in $(seq 1 9); do
        tags=$((1 << (i - 1)))
        # focus tag
        riverctl map normal $mod        "$i" set-focused-tags "$tags"
        # move view to tag
        riverctl map normal $mod+Shift  "$i" set-view-tags    "$tags"
        # toggle tag visibility
        riverctl map normal $mod+Control "$i" toggle-focused-tags "$tags"
    done

    # All-tags scratchpad (tag 0 = all 32 tags visible)
    all_tags=$(((1 << 32) - 1))
    riverctl map normal $mod+Shift S toggle-view-tags "$all_tags"

    # ── Scratchpad (tag 32) ──────────────────────────────────────────────────
    scratch_tag=$((1 << 31))
    riverctl map normal $mod S toggle-focused-tags "$scratch_tag"

    # ── Screenshots ──────────────────────────────────────────────────────────
    riverctl map normal None        Print  spawn 'grim -g "$(slurp)" - | wl-copy'
    riverctl map normal $mod        Print  spawn 'grim - | wl-copy'
    riverctl map normal $mod+Shift  Print  spawn 'grim -g "$(slurp)" ~/Pictures/screenshot-$(date +%Y%m%d-%H%M%S).png'

    # ── Clipboard ────────────────────────────────────────────────────────────
    riverctl map normal $mod C spawn 'cliphist list | nixprism --dmenu | cliphist decode | wl-copy'

    # ── Lock ─────────────────────────────────────────────────────────────────
    riverctl map normal $mod+Shift+Control L spawn 'hyprlock'

    # ── Audio ────────────────────────────────────────────────────────────────
    riverctl map normal None XF86AudioMute        spawn 'pamixer -t'
    riverctl map normal None XF86AudioMicMute     spawn 'pamixer --default-source -t'
    riverctl map -repeat normal None XF86AudioRaiseVolume spawn 'pamixer -i 5'
    riverctl map -repeat normal None XF86AudioLowerVolume spawn 'pamixer -d 5'

    # ── Media ────────────────────────────────────────────────────────────────
    riverctl map normal None XF86AudioPlay spawn 'playerctl play-pause'
    riverctl map normal None XF86AudioPrev spawn 'playerctl previous'
    riverctl map normal None XF86AudioNext spawn 'playerctl next'

    # ── Brightness ───────────────────────────────────────────────────────────
    riverctl map -repeat normal None XF86MonBrightnessUp   spawn 'brightnessctl set 5%+'
    riverctl map -repeat normal None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'

    # ── Mouse binds ──────────────────────────────────────────────────────────
    riverctl map-pointer normal $mod BTN_LEFT  move-view
    riverctl map-pointer normal $mod BTN_RIGHT resize-view
    riverctl map-pointer normal $mod BTN_MIDDLE toggle-float

    # ── Floating window rules ────────────────────────────────────────────────
    riverctl rule-add -app-id 'nm-connection-editor' float
    riverctl rule-add -app-id 'pavucontrol'           float
    riverctl rule-add -app-id 'blueman-manager'       float

    # ── Startup ──────────────────────────────────────────────────────────────
    ${pkgs.polkit_gnome}/libexec/polkit-gnome-authentication-agent-1 &
    nm-applet --indicator &
    wl-paste --type text  --watch cliphist store &
    wl-paste --type image --watch cliphist store &

    # ── Layout generator ─────────────────────────────────────────────────────
    riverctl default-layout rivertile
    ${layoutCmd}
  '';

in
lib.mkIf cfg.enable {

  # ── Packages ─────────────────────────────────────────────────────────────
  home.packages = with pkgs; [
    river
    rivertile       # tiling layout generator
    grim            # screenshot
    slurp           # screen area selector
    wl-clipboard    # wl-copy / wl-paste
    pamixer         # audio control
    playerctl       # media keys
    brightnessctl   # backlight
  ];

  # ── River init script ─────────────────────────────────────────────────────
  # River reads ~/.config/river/init on startup (must be executable).
  home.file.".config/river/init" = {
    executable = true;
    text       = initScript;
  };

  # ── Environment variables ─────────────────────────────────────────────────
  home.sessionVariables = {
    XDG_SESSION_TYPE          = "wayland";
    XDG_CURRENT_DESKTOP       = "river";
    QT_QPA_PLATFORM           = "wayland";
    QT_WAYLAND_DISABLE_WINDOWDECORATION = "1";
    GDK_BACKEND               = "wayland,x11,*";
    MOZ_ENABLE_WAYLAND        = "1";
    XCURSOR_SIZE              = "24";
  };
}
